### ISSUE TITLE
Some sounds remain even if SFX turned off in settings

### ISSUE THREAD

**Issue by dimoonchepe** [shishkabob27/CardWars#5]
When turning on SFX in setings, there are still some sounds audible during the game. I've found the following cases:

- taking damage on hero
- chest appearance
- playing spell card

**Comment by Saito197** [comment]
I found the problem, a lot of effects are handled by spawning an instance of a prefab that contains an AudioSource with "Play on Awake" enabled, thus they are independent from SLOTAudioManager. You can see all SFXs played this way in /Assets/PrefabInstance/FX_* 

@shishkabob27 would you mind if I work on this?

**Comment by shishkabob27** [comment]
@Saito197 I don’t mind, thank you for finding the problem!
